baseURL = "http://gitlab.dysbeat.fr/"
languageCode = "en-us"
title = "Roll'in club dunkerque"
theme = "minimal"
googleAnalytics = ""

[params]
    logo = "header.png"
    accent = "grey"
    showBorder = true
    mathjax = false
    backgroundColor = "white"
    font = "Source Code Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = []
    description = "Adresse: Salle de sport du lycée de l'Europe</br> 809 Rue du Banc vert</br> 59640 Dunkerque"

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/team/"
    name = "Equipes"
    weight = 2

[[menu.main]]
    url = "/results/"
    name = "Resultats"
    weight = 3

[[menu.main]]
    url = "/player/"
    name = "Joueurs"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "rollinclub.dunkerque@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 2

