export const seasons_data = [{
  year: '2016-2017',
  rankings: [
  {"rank": "Pl", "teams": "Equipe", "points": "Pts", "played": "J.", "wins": "V.", "draws": "E.", "loses": "P.", "forfaited": "F.", "goals": "buts", "goalsAllowed": "BE.", "goalsDiff": "diff."},
  {"rank": "1", "teams": "Tourcoing ", "points": "10", "played": "0", "wins": "0", "draws": "0", "loses": "0", "forfaited": "0", "goals": "101", "goalsAllowed": "33", "goalsDiff": "68"},
  {"rank": "2", "teams": "Camon ", "points": "4", "played": "0", "wins": "0", "draws": "0", "loses": "3", "forfaited": "0", "goals": "46", "goalsAllowed": "36", "goalsDiff": "10"},
  {"rank": "3", "teams": "Pont de Metz", "points": "4", "played": "0", "wins": "0", "draws": "0", "loses": "4", "forfaited": "0", "goals": "54", "goalsAllowed": "53", "goalsDiff": "1"},
  {"rank": "4", "teams": "Amiens ", "points": "2", "played": "0", "wins": "0", "draws": "0", "loses": "3", "forfaited": "0", "goals": "18", "goalsAllowed": "37", "goalsDiff": "-19"},
  {"rank": "5", "teams": "Dunkerque", "points": "2", "played": "0", "wins": "0", "draws": "1", "loses": "4", "forfaited": "0", "goals": "46", "goalsAllowed": "50", "goalsDiff": "-4"},
  {"rank": "6", "teams": "Boulogne sur Mer", "points": "0", "played": "0", "wins": "0", "draws": "1", "loses": "7", "forfaited": "0", "goals": "21", "goalsAllowed": "77", "goalsDiff": "-56"}
  ],
  results: [
  {"date": "06/11/2016", "day": "1", "ateam": "Dunkerque", "ascore": "4", "bteam": "Tourcoing", "bscore": "5", "schedule": "12:00", "place": "tourcoing"},
  {"date": "06/11/2016", "day": "1", "ateam": "Amiens", "ascore": "4", "bteam": "Camon", "bscore": "7", "schedule": "15:00", "place": "amiens"},
  {"date": "19/11/2016", "day": "2", "ateam": "Tourcoing", "ascore": "13", "bteam": "Amiens", "bscore": "3", "schedule": "18:30", "place": "tourcoing"},
  {"date": "19/11/2016", "day": "2", "ateam": "Dunkerque", "ascore": "", "bteam": "Camon", "bscore": "", "schedule": "20:30", "place": "tourcoing"},
  {"date": "20/11/2016", "day": "2", "ateam": "Pont de Metz", "ascore": "13", "bteam": "Boulogne sur Mer", "bscore": "3", "schedule": "10:00", "place": "pont de metz"},
  {"date": "26/11/2016", "day": "3", "ateam": "Amiens", "ascore": "", "bteam": "Boulogne sur Mer", "bscore": "", "schedule": "16:00", "place": "pont de metz"},
  {"date": "26/11/2016", "day": "3", "ateam": "Pont de Metz", "ascore": "7", "bteam": "Tourcoing", "bscore": "8", "schedule": "18:00", "place": "pont de metz"},
  {"date": "03/12/2016", "day": "4", "ateam": "Pont de Metz", "ascore": "7", "bteam": "Dunkerque", "bscore": "5", "schedule": "15:30", "place": "pont de metz"},
  {"date": "03/12/2016", "day": "4", "ateam": "Camon", "ascore": "9", "bteam": "Boulogne sur Mer", "bscore": "2", "schedule": "21:50", "place": "amiens"},
  {"date": "10/12/2016", "day": "5", "ateam": "Tourcoing", "ascore": "8", "bteam": "Camon", "bscore": "3", "schedule": "20:00", "place": "tourcoing"},
  {"date": "18/12/2016", "day": "5", "ateam": "Dunkerque", "ascore": "F", "bteam": "Amiens", "bscore": "5", "schedule": "14:00", "place": "amiens"},
  {"date": "08/01/2017", "day": "6", "ateam": "Pont de Metz", "ascore": "9", "bteam": "Camon", "bscore": "5", "schedule": "10:00", "place": "pont de metz"},
  {"date": "08/01/2017", "day": "6", "ateam": "Dunkerque", "ascore": "16", "bteam": "Boulogne sur Mer", "bscore": "4", "schedule": "12:00", "place": "tourcoing"},
  {"date": "11/03/2017", "day": "7", "ateam": "Tourcoing", "ascore": "14", "bteam": "Boulogne sur Mer", "bscore": "0", "schedule": "20:30", "place": "lille"},
  {"date": "21/01/2017", "day": "8", "ateam": "Tourcoing", "ascore": "10", "bteam": "Dunkerque", "bscore": "6", "schedule": "20:00", "place": "tourcoing"},
  {"date": "29/01/2017", "day": "9", "ateam": "Boulogne sur Mer", "ascore": "3", "bteam": "Pont de Metz", "bscore": "9", "schedule": "10:00", "place": "boulogne"},
  {"date": "29/01/2017", "day": "9", "ateam": "Amiens", "ascore": "2", "bteam": "Tourcoing", "bscore": "14", "schedule": "15:00", "place": "amiens"},
  {"date": "05/02/2017", "day": "10", "ateam": "Boulogne sur Mer", "ascore": "3", "bteam": "Amiens", "bscore": "4", "schedule": "10:00", "place": "boulogne"},
  {"date": "05/02/2017", "day": "10", "ateam": "Tourcoing", "ascore": "15", "bteam": "Pont de Metz", "bscore": "4", "schedule": "12:00", "place": "tourcoing"},
  {"date": "05/02/2017", "day": "10", "ateam": "Camon", "ascore": "13", "bteam": "Dunkerque", "bscore": "4", "schedule": "14:00", "place": "amiens"},
  {"date": "05/03/2017", "day": "11", "ateam": "Boulogne sur Mer", "ascore": "", "bteam": "Camon", "bscore": "", "schedule": "10:00", "place": "boulogne"},
  {"date": "02/04/2017", "day": "11", "ateam": "Dunkerque", "ascore": "7", "bteam": "Pont de Metz", "bscore": "2", "schedule": "12:00", "place": "boulogne"},
  {"date": "12/03/2017", "day": "12", "ateam": "Camon", "ascore": "2", "bteam": "Tourcoing", "bscore": "6", "schedule": "14:00", "place": "amiens"},
  {"date": "19/03/2017", "day": "13", "ateam": "Boulogne sur Mer", "ascore": "4", "bteam": "Dunkerque", "bscore": "4", "schedule": "10:00", "place": "boulogne"},
  {"date": "19/03/2017", "day": "13", "ateam": "Camon", "ascore": "7", "bteam": "Pont de Metz", "bscore": "3", "schedule": "14:00", "place": "amiens"},
  {"date": "25/03/2017", "day": "14", "ateam": "Pont de Metz", "ascore": "", "bteam": "Amiens", "bscore": "", "schedule": "18:00", "place": "pont de metz"},
  {"date": "26/03/2017", "day": "14", "ateam": "Boulogne sur Mer", "ascore": "2", "bteam": "Tourcoing", "bscore": "8", "schedule": "10:00", "place": "boulogne"}
  ]
  },
  {
  year: '2017-2018',
  rankings: [
  {"rank": "Pl", "teams": "Equipe", "points": "Pts", "played": "J.", "wins": "V.", "draws": "E.", "loses": "P.", "forfaited": "F.", "goals": "buts", "goalsAllowed": "BE.", "goalsDiff": "diff."},
  {"rank": "1", "teams": "Camon ", "points": "11", "played": "0", "wins": "0", "draws": "2", "loses": "1", "forfaited": "0", "goals": "141", "goalsAllowed": "39", "goalsDiff": "102"},
  {"rank": "2", "teams": "Bethune", "points": "10", "played": "0", "wins": "0", "draws": "1", "loses": "2", "forfaited": "0", "goals": "99", "goalsAllowed": "44", "goalsDiff": "55"},
  {"rank": "3", "teams": "Pont de Metz", "points": "8", "played": "0", "wins": "0", "draws": "0", "loses": "5", "forfaited": "0", "goals": "108", "goalsAllowed": "56", "goalsDiff": "52"},
  {"rank": "4", "teams": "Dunkerque", "points": "8", "played": "0", "wins": "0", "draws": "2", "loses": "2", "forfaited": "0", "goals": "116", "goalsAllowed": "69", "goalsDiff": "47"},
  {"rank": "5", "teams": "Boulogne sur Mer", "points": "4", "played": "0", "wins": "0", "draws": "0", "loses": "9", "forfaited": "0", "goals": "44", "goalsAllowed": "124", "goalsDiff": "-80"},
  {"rank": "6", "teams": "Amiens ", "points": "4", "played": "0", "wins": "0", "draws": "0", "loses": "6", "forfaited": "0", "goals": "54", "goalsAllowed": "79", "goalsDiff": "-25"},
  {"rank": "7", "teams": "Valenciennes ", "points": "2", "played": "0", "wins": "0", "draws": "1", "loses": "7", "forfaited": "0", "goals": "69", "goalsAllowed": "96", "goalsDiff": "-27"},
  {"rank": "8", "teams": "Arras-Vyruce", "points": "0", "played": "0", "wins": "0", "draws": "0", "loses": "9", "forfaited": "0", "goals": "18", "goalsAllowed": "142", "goalsDiff": "-124"}
  ],
  results: [
  {"date": "29/10/2017", "day": "1", "ateam": "Arras-Vyruce", "ascore": "1", "bteam": "Camon", "bscore": "19", "schedule": "10:15", "place": "st catherine les arras"},
  {"date": "29/10/2017", "day": "1", "ateam": "Valenciennes ", "ascore": "7", "bteam": "Boulogne sur Mer", "bscore": "5", "schedule": "12:00", "place": "st catherine les arras"},
  {"date": "29/10/2017", "day": "1", "ateam": "Bethune", "ascore": "7", "bteam": "Dunkerque", "bscore": "2", "schedule": "14:00", "place": "st catherine les arras"},
  {"date": "11/11/2017", "day": "1", "ateam": "Pont de Metz", "ascore": "10", "bteam": "Amiens", "bscore": "7", "schedule": "20:30", "place": "pont de metz"},
  {"date": "05/11/2017", "day": "2", "ateam": "Boulogne sur Mer", "ascore": "2", "bteam": "Camon", "bscore": "10", "schedule": "09:00", "place": "boulogne"},
  {"date": "05/11/2017", "day": "2", "ateam": "Arras-Vyruce", "ascore": "3", "bteam": "Bethune", "bscore": "12", "schedule": "09:00", "place": "st catherine les arras"},
  {"date": "05/11/2017", "day": "2", "ateam": "Valenciennes ", "ascore": "7", "bteam": "Amiens", "bscore": "9", "schedule": "11:00", "place": "st catherine les arras"},
  {"date": "05/11/2017", "day": "2", "ateam": "Dunkerque", "ascore": "10", "bteam": "Pont de Metz", "bscore": "7", "schedule": "12:00", "place": "boulogne"},
  {"date": "18/11/2017", "day": "3", "ateam": "Pont de Metz", "ascore": "11", "bteam": "Valenciennes ", "bscore": "8", "schedule": "20:00", "place": "pont de metz"},
  {"date": "19/11/2017", "day": "3", "ateam": "Boulogne sur Mer", "ascore": "2", "bteam": "Dunkerque", "bscore": "10", "schedule": "10:00", "place": "boulogne"},
  {"date": "19/11/2017", "day": "3", "ateam": "Arras-Vyruce", "ascore": "3", "bteam": "Amiens", "bscore": "8", "schedule": "10:00", "place": "st catherine les arras"},
  {"date": "19/11/2017", "day": "3", "ateam": "Bethune", "ascore": "7", "bteam": "Camon", "bscore": "4", "schedule": "12:00", "place": "boulogne"},
  {"date": "26/11/2017", "day": "4", "ateam": "Dunkerque", "ascore": "16", "bteam": "Arras-Vyruce", "bscore": "3", "schedule": "09:00", "place": "boulogne"},
  {"date": "26/11/2017", "day": "4", "ateam": "Camon", "ascore": "14", "bteam": "Valenciennes ", "bscore": "3", "schedule": "10:00", "place": "amiens"},
  {"date": "26/11/2017", "day": "4", "ateam": "Boulogne sur Mer", "ascore": "1", "bteam": "Pont de Metz", "bscore": "20", "schedule": "11:00", "place": "boulogne"},
  {"date": "26/11/2017", "day": "4", "ateam": "Bethune", "ascore": "9", "bteam": "Amiens", "bscore": "2", "schedule": "13:00", "place": "boulogne"},
  {"date": "03/12/2017", "day": "5", "ateam": "Amiens", "ascore": "2", "bteam": "Camon", "bscore": "10", "schedule": "09:00", "place": "amiens"},
  {"date": "03/12/2017", "day": "5", "ateam": "Arras-Vyruce", "ascore": "1", "bteam": "Boulogne sur Mer", "bscore": "6", "schedule": "10:00", "place": "st catherine les arras"},
  {"date": "03/12/2017", "day": "5", "ateam": "Valenciennes ", "ascore": "9", "bteam": "Dunkerque", "bscore": "9", "schedule": "12:10", "place": "st catherine les arras"},
  {"date": "03/12/2017", "day": "5", "ateam": "Bethune", "ascore": "1", "bteam": "Pont de Metz", "bscore": "2", "schedule": "14:00", "place": "st catherine les arras"},
  {"date": "06/01/2018", "day": "6", "ateam": "Pont de Metz", "ascore": "3", "bteam": "Camon", "bscore": "6", "schedule": "20:00", "place": "pont de metz"},
  {"date": "08/04/2018", "day": "6", "ateam": "Dunkerque", "ascore": "10", "bteam": "Amiens", "bscore": "6", "schedule": "10:00", "place": "boulogne"},
  {"date": "08/04/2018", "day": "6", "ateam": "Valenciennes ", "ascore": "", "bteam": "Arras-Vyruce", "bscore": "", "schedule": "10:00", "place": "sainte catherine les arras"},
  {"date": "08/04/2018", "day": "6", "ateam": "Boulogne sur Mer", "ascore": "2", "bteam": "Bethune", "bscore": "15", "schedule": "12:30", "place": "boulogne"},
  {"date": "14/01/2018", "day": "7", "ateam": "Boulogne sur Mer", "ascore": "5", "bteam": "Amiens", "bscore": "F", "schedule": "10:00", "place": "boulogne"},
  {"date": "14/01/2018", "day": "7", "ateam": "Arras-Vyruce", "ascore": "1", "bteam": "Pont de Metz", "bscore": "10", "schedule": "10:00", "place": "sainte catherine les arras"},
  {"date": "14/01/2018", "day": "7", "ateam": "Bethune", "ascore": "9", "bteam": "Valenciennes ", "bscore": "4", "schedule": "12:00", "place": "sainte catherine les arras"},
  {"date": "14/01/2018", "day": "7", "ateam": "Dunkerque", "ascore": "6", "bteam": "Camon", "bscore": "6", "schedule": "12:00", "place": "boulogne"},
  {"date": "28/01/2018", "day": "8", "ateam": "Dunkerque", "ascore": "7", "bteam": "Bethune", "bscore": "3", "schedule": "10:00", "place": "boulogne"},
  {"date": "28/01/2018", "day": "8", "ateam": "Camon", "ascore": "19", "bteam": "Arras-Vyruce", "bscore": "1", "schedule": "11:00", "place": "amiens"},
  {"date": "28/01/2018", "day": "8", "ateam": "Boulogne sur Mer", "ascore": "5", "bteam": "Valenciennes ", "bscore": "3", "schedule": "12:00", "place": "boulogne"},
  {"date": "11/03/2018", "day": "8", "ateam": "Amiens", "ascore": "6", "bteam": "Pont de Metz", "bscore": "3", "schedule": "10:00", "place": "amiens"},
  {"date": "10/02/2018", "day": "9", "ateam": "Pont de Metz", "ascore": "12", "bteam": "Dunkerque", "bscore": "4", "schedule": "20:30", "place": "pont de metz"},
  {"date": "10/02/2018", "day": "9", "ateam": "Camon", "ascore": "14", "bteam": "Boulogne sur Mer", "bscore": "0", "schedule": "20:30", "place": "amiens"},
  {"date": "11/02/2018", "day": "9", "ateam": "Amiens", "ascore": "9", "bteam": "Valenciennes ", "bscore": "7", "schedule": "12:25", "place": "amiens"},
  {"date": "11/02/2018", "day": "9", "ateam": "Bethune", "ascore": "5", "bteam": "Arras-Vyruce", "bscore": "F", "schedule": "13:00", "place": "lambersart"},
  {"date": "17/02/2018", "day": "10", "ateam": "Valenciennes ", "ascore": "F", "bteam": "Pont de Metz", "bscore": "5", "schedule": "18:30", "place": "tourcoing"},
  {"date": "25/02/2018", "day": "10", "ateam": "Dunkerque", "ascore": "13", "bteam": "Boulogne sur Mer", "bscore": "7", "schedule": "10:00", "place": "boulogne"},
  {"date": "25/02/2018", "day": "10", "ateam": "Amiens", "ascore": "", "bteam": "Arras-Vyruce", "bscore": "", "schedule": "10:00", "place": "amiens"},
  {"date": "25/02/2018", "day": "10", "ateam": "Camon", "ascore": "8", "bteam": "Bethune", "bscore": "8", "schedule": "12:00", "place": "amiens"},
  {"date": "03/03/2018", "day": "11", "ateam": "Pont de Metz", "ascore": "20", "bteam": "Boulogne sur Mer", "bscore": "1", "schedule": "20:30", "place": "pont de metz"},
  {"date": "04/03/2018", "day": "11", "ateam": "Arras-Vyruce", "ascore": "2", "bteam": "Dunkerque", "bscore": "24", "schedule": "09:00", "place": "sainte catherine les arras"},
  {"date": "04/03/2018", "day": "11", "ateam": "Amiens", "ascore": "3", "bteam": "Bethune", "bscore": "7", "schedule": "10:00", "place": "amiens"},
  {"date": "04/03/2018", "day": "11", "ateam": "Valenciennes ", "ascore": "3", "bteam": "Camon", "bscore": "12", "schedule": "11:00", "place": "sainte catherine les arras"},
  {"date": "17/03/2018", "day": "12", "ateam": "Camon", "ascore": "8", "bteam": "Amiens", "bscore": "2", "schedule": "18:10", "place": "amiens"},
  {"date": "18/03/2018", "day": "12", "ateam": "Boulogne sur Mer", "ascore": "5", "bteam": "Arras-Vyruce", "bscore": "F", "schedule": "10:00", "place": "boulogne"},
  {"date": "18/03/2018", "day": "12", "ateam": "Pont de Metz", "ascore": "4", "bteam": "Bethune", "bscore": "5", "schedule": "11:00", "place": "pont de metz"},
  {"date": "18/03/2018", "day": "12", "ateam": "Dunkerque", "ascore": "5", "bteam": "Valenciennes ", "bscore": "F", "schedule": "12:00", "place": "boulogne"},
  {"date": "25/03/2018", "day": "13", "ateam": "Camon", "ascore": "6", "bteam": "Pont de Metz", "bscore": "1", "schedule": "09:00", "place": "amiens"},
  {"date": "25/03/2018", "day": "13", "ateam": "Arras-Vyruce", "ascore": "3", "bteam": "Valenciennes ", "bscore": "18", "schedule": "10:00", "place": "sainte catherine les arras"},
  {"date": "25/03/2018", "day": "13", "ateam": "Amiens", "ascore": "", "bteam": "Dunkerque", "bscore": "", "schedule": "11:00", "place": "amiens"},
  {"date": "25/03/2018", "day": "13", "ateam": "Bethune", "ascore": "11", "bteam": "Boulogne sur Mer", "bscore": "3", "schedule": "12:00", "place": "sainte catherine les arras"},
  {"date": "31/03/2018", "day": "14", "ateam": "Pont de Metz", "ascore": "", "bteam": "Arras-Vyruce", "bscore": "", "schedule": "20:00", "place": "pont de metz"},
  {"date": "01/04/2018", "day": "14", "ateam": "Amiens", "ascore": "", "bteam": "Boulogne sur Mer", "bscore": "", "schedule": "10:00", "place": "amiens"},
  {"date": "01/04/2018", "day": "14", "ateam": "Valenciennes ", "ascore": "", "bteam": "Bethune", "bscore": "", "schedule": "12:00", "place": "amiens"},
  {"date": "01/04/2018", "day": "14", "ateam": "Camon", "ascore": "5", "bteam": "Dunkerque", "bscore": "F", "schedule": "14:00", "place": "pont de metz"}
  ]
  },
  {
  year: '2018-2019',
  rankings: [
  {"rank": "Pl", "teams": "Equipe", "points": "Pts", "played": "J.", "wins": "V.", "draws": "E.", "loses": "P.", "forfaited": "F.", "goals": "buts", "goalsAllowed": "BE.", "goalsDiff": "diff."},
  {"rank": "1", "teams": "Amiens ", "points": "11", "played": "0", "wins": "0", "draws": "0", "loses": "1", "forfaited": "0", "goals": "87", "goalsAllowed": "32", "goalsDiff": "55"},
  {"rank": "2", "teams": "Bethune", "points": "9", "played": "0", "wins": "0", "draws": "0", "loses": "3", "forfaited": "0", "goals": "104", "goalsAllowed": "55", "goalsDiff": "49"},
  {"rank": "3", "teams": "Pont de Metz", "points": "8", "played": "0", "wins": "0", "draws": "0", "loses": "4", "forfaited": "0", "goals": "82", "goalsAllowed": "68", "goalsDiff": "14"},
  {"rank": "4", "teams": "Dunkerque", "points": "7", "played": "0", "wins": "0", "draws": "1", "loses": "2", "forfaited": "0", "goals": "98", "goalsAllowed": "60", "goalsDiff": "38"},
  {"rank": "5", "teams": "Valenciennes ", "points": "3", "played": "0", "wins": "0", "draws": "1", "loses": "7", "forfaited": "0", "goals": "65", "goalsAllowed": "100", "goalsDiff": "-35"},
  {"rank": "6", "teams": "Boulogne sur Mer", "points": "2", "played": "0", "wins": "0", "draws": "0", "loses": "10", "forfaited": "0", "goals": "66", "goalsAllowed": "102", "goalsDiff": "-36"},
  {"rank": "7", "teams": "Moreuil", "points": "0", "played": "0", "wins": "0", "draws": "0", "loses": "10", "forfaited": "0", "goals": "53", "goalsAllowed": "138", "goalsDiff": "-85"}
  ],
  results: [
  {"date": "21/10/2018", "day": "1", "ateam": "Boulogne sur Mer", "ascore": "4", "bteam": "Amiens", "bscore": "7", "schedule": "10:00", "place": "boulogne"},
  {"date": "21/10/2018", "day": "1", "ateam": "Dunkerque", "ascore": "22", "bteam": "Moreuil", "bscore": "2", "schedule": "12:00", "place": "boulogne"},
  {"date": "07/04/2019", "day": "1", "ateam": "Pont de Metz", "ascore": "8", "bteam": "Valenciennes ", "bscore": "3", "schedule": "11:00", "place": "pont de metz"},
  {"date": "11/11/2018", "day": "2", "ateam": "Pont de Metz", "ascore": "2", "bteam": "Amiens", "bscore": "5", "schedule": "10:00", "place": "pont de metz"},
  {"date": "11/11/2018", "day": "2", "ateam": "Bethune", "ascore": "1", "bteam": "Dunkerque", "bscore": "7", "schedule": "12:00", "place": "pont de metz"},
  {"date": "11/11/2018", "day": "2", "ateam": "Boulogne sur Mer", "ascore": "12", "bteam": "Moreuil", "bscore": "3", "schedule": "14:00", "place": "pont de metz"},
  {"date": "18/11/2018", "day": "3", "ateam": "Moreuil", "ascore": "4", "bteam": "Pont de Metz", "bscore": "15", "schedule": "10:00", "place": "moreuil"},
  {"date": "18/11/2018", "day": "3", "ateam": "Bethune", "ascore": "16", "bteam": "Valenciennes ", "bscore": "3", "schedule": "12:00", "place": "moreuil"},
  {"date": "18/11/2018", "day": "3", "ateam": "Dunkerque", "ascore": "F", "bteam": "Amiens", "bscore": "5", "schedule": "14:00", "place": "moreuil"},
  {"date": "02/12/2018", "day": "4", "ateam": "Amiens", "ascore": "9", "bteam": "Bethune", "bscore": "5", "schedule": "10:00", "place": "amiens"},
  {"date": "02/12/2018", "day": "4", "ateam": "Pont de Metz", "ascore": "7", "bteam": "Boulogne sur Mer", "bscore": "5", "schedule": "12:00", "place": "amiens"},
  {"date": "02/12/2018", "day": "4", "ateam": "Dunkerque", "ascore": "11", "bteam": "Valenciennes ", "bscore": "11", "schedule": "14:00", "place": "amiens"},
  {"date": "09/12/2018", "day": "5", "ateam": "Bethune", "ascore": "15", "bteam": "Moreuil", "bscore": "2", "schedule": "10:00", "place": "boulogne"},
  {"date": "09/12/2018", "day": "5", "ateam": "Dunkerque", "ascore": "15", "bteam": "Boulogne sur Mer", "bscore": "6", "schedule": "12:00", "place": "boulogne"},
  {"date": "09/12/2018", "day": "5", "ateam": "Amiens", "ascore": "10", "bteam": "Valenciennes ", "bscore": "5", "schedule": "14:00", "place": "boulogne"},
  {"date": "16/12/2018", "day": "6", "ateam": "Valenciennes ", "ascore": "15", "bteam": "Moreuil", "bscore": "10", "schedule": "10:00", "place": "pont de metz"},
  {"date": "16/12/2018", "day": "6", "ateam": "Boulogne sur Mer", "ascore": "3", "bteam": "Bethune", "bscore": "16", "schedule": "12:00", "place": "pont de metz"},
  {"date": "16/12/2018", "day": "6", "ateam": "Pont de Metz", "ascore": "7", "bteam": "Dunkerque", "bscore": "11", "schedule": "14:00", "place": "pont de metz"},
  {"date": "13/01/2019", "day": "7", "ateam": "Moreuil", "ascore": "1", "bteam": "Amiens", "bscore": "8", "schedule": "10:00", "place": "moreuil"},
  {"date": "13/01/2019", "day": "7", "ateam": "Valenciennes ", "ascore": "9", "bteam": "Boulogne sur Mer", "bscore": "4", "schedule": "12:00", "place": "moreuil"},
  {"date": "13/01/2019", "day": "7", "ateam": "Bethune", "ascore": "4", "bteam": "Pont de Metz", "bscore": "8", "schedule": "14:05", "place": "moreuil"},
  {"date": "20/01/2019", "day": "8", "ateam": "Amiens", "ascore": "7", "bteam": "Boulogne sur Mer", "bscore": "3", "schedule": "10:00", "place": "boulogne"},
  {"date": "20/01/2019", "day": "8", "ateam": "Valenciennes ", "ascore": "2", "bteam": "Pont de Metz", "bscore": "6", "schedule": "12:00", "place": "boulogne"},
  {"date": "20/01/2019", "day": "8", "ateam": "Moreuil", "ascore": "F", "bteam": "Dunkerque", "bscore": "5", "schedule": "12:00", "place": "boulogne"},
  {"date": "27/01/2019", "day": "9", "ateam": "Bethune", "ascore": "3", "bteam": "Amiens", "bscore": "1", "schedule": "10:00", "place": "boulogne"},
  {"date": "27/01/2019", "day": "9", "ateam": "Boulogne sur Mer", "ascore": "2", "bteam": "Pont de Metz", "bscore": "6", "schedule": "12:35", "place": "boulogne"},
  {"date": "27/01/2019", "day": "9", "ateam": "Valenciennes ", "ascore": "2", "bteam": "Dunkerque", "bscore": "11", "schedule": "14:00", "place": "boulogne"},
  {"date": "03/02/2019", "day": "10", "ateam": "Amiens", "ascore": "10", "bteam": "Pont de Metz", "bscore": "1", "schedule": "10:00", "place": "pont de metz"},
  {"date": "03/02/2019", "day": "10", "ateam": "Dunkerque", "ascore": "5", "bteam": "Bethune", "bscore": "8", "schedule": "12:00", "place": "pont de metz"},
  {"date": "03/02/2019", "day": "10", "ateam": "Moreuil", "ascore": "11", "bteam": "Boulogne sur Mer", "bscore": "15", "schedule": "14:00", "place": "moreuil"},
  {"date": "10/02/2019", "day": "11", "ateam": "Moreuil", "ascore": "6", "bteam": "Bethune", "bscore": "12", "schedule": "10:00", "place": "moreuil"},
  {"date": "10/02/2019", "day": "11", "ateam": "Boulogne sur Mer", "ascore": "5", "bteam": "Dunkerque", "bscore": "6", "schedule": "10:00", "place": "boulogne sur mer"},
  {"date": "10/02/2019", "day": "11", "ateam": "Valenciennes ", "ascore": "2", "bteam": "Amiens", "bscore": "10", "schedule": "12:00", "place": "moreuil"},
  {"date": "10/03/2019", "day": "12", "ateam": "Amiens", "ascore": "10", "bteam": "Moreuil", "bscore": "6", "schedule": "10:00", "place": "moreuil"},
  {"date": "10/03/2019", "day": "12", "ateam": "Boulogne sur Mer", "ascore": "5", "bteam": "Valenciennes ", "bscore": "9", "schedule": "10:00", "place": "boulogne"},
  {"date": "10/03/2019", "day": "12", "ateam": "Pont de Metz", "ascore": "5", "bteam": "Bethune", "bscore": "9", "schedule": "12:00", "place": "boulogne"},
  {"date": "17/03/2019", "day": "13", "ateam": "Pont de Metz", "ascore": "9", "bteam": "Moreuil", "bscore": "8", "schedule": "10:00", "place": "amiens"},
  {"date": "17/03/2019", "day": "13", "ateam": "Valenciennes ", "ascore": "4", "bteam": "Bethune", "bscore": "9", "schedule": "12:00", "place": "amiens"},
  {"date": "17/03/2019", "day": "13", "ateam": "Amiens", "ascore": "5", "bteam": "Dunkerque", "bscore": "F", "schedule": "14:00", "place": "amiens"},
  {"date": "24/03/2019", "day": "14", "ateam": "Dunkerque", "ascore": "5", "bteam": "Pont de Metz", "bscore": "8", "schedule": "10:00", "place": "moreuil"},
  {"date": "24/03/2019", "day": "14", "ateam": "Bethune", "ascore": "6", "bteam": "Boulogne sur Mer", "bscore": "2", "schedule": "12:00", "place": "moreuil"},
  {"date": "24/03/2019", "day": "14", "ateam": "Moreuil", "ascore": "", "bteam": "Valenciennes ", "bscore": "", "schedule": "14:00", "place": "moreuil"}
  ]
  },
  {
  year: '2019-2020',
  rankings: [
  {"rank": "Pl", "teams": "Equipe", "points": "Pts", "played": "J.", "wins": "V.", "draws": "E.", "loses": "P.", "forfaited": "F.", "goals": "buts", "goalsAllowed": "BE.", "goalsDiff": "diff."},
  {"rank": "1", "teams": "Dunkerque", "points": "4", "played": "0", "wins": "0", "draws": "0", "loses": "1", "forfaited": "0", "goals": "47", "goalsAllowed": "30", "goalsDiff": "17"},
  {"rank": "2", "teams": "Boulogne sur Mer", "points": "2", "played": "0", "wins": "0", "draws": "1", "loses": "2", "forfaited": "0", "goals": "32", "goalsAllowed": "34", "goalsDiff": "-2"},
  {"rank": "3", "teams": "Douai", "points": "1", "played": "0", "wins": "0", "draws": "3", "loses": "0", "forfaited": "0", "goals": "24", "goalsAllowed": "19", "goalsDiff": "5"},
  {"rank": "4", "teams": "Bethune", "points": "1", "played": "0", "wins": "0", "draws": "2", "loses": "2", "forfaited": "0", "goals": "25", "goalsAllowed": "27", "goalsDiff": "-2"},
  {"rank": "5", "teams": "Valenciennes ", "points": "1", "played": "0", "wins": "0", "draws": "0", "loses": "3", "forfaited": "0", "goals": "26", "goalsAllowed": "44", "goalsDiff": "-18"}
  ],
  results: [
  {"date": "17/11/2019", "day": "1", "ateam": "Boulogne sur Mer", "ascore": "7", "bteam": "Dunkerque", "bscore": "8", "schedule": "09:00", "place": "boulogne sur mer"},
  {"date": "17/11/2019", "day": "1", "ateam": "Douai", "ascore": "10", "bteam": "Valenciennes ", "bscore": "5", "schedule": "11:00", "place": "boulogne sur mer"},
  {"date": "24/11/2019", "day": "2", "ateam": "Boulogne sur Mer", "ascore": "6", "bteam": "Douai", "bscore": "6", "schedule": "09:00", "place": "boulogne sur mer"},
  {"date": "24/11/2019", "day": "2", "ateam": "Bethune", "ascore": "5", "bteam": "Dunkerque", "bscore": "10", "schedule": "11:00", "place": "boulogne sur mer"},
  {"date": "08/12/2019", "day": "3", "ateam": "Douai", "ascore": "5", "bteam": "Bethune", "bscore": "5", "schedule": "09:00", "place": "boulogne sur mer"},
  {"date": "08/12/2019", "day": "3", "ateam": "Boulogne sur Mer", "ascore": "7", "bteam": "Valenciennes ", "bscore": "6", "schedule": "11:20", "place": "boulogne sur mer"},
  {"date": "15/12/2019", "day": "4", "ateam": "Boulogne sur Mer", "ascore": "9", "bteam": "Bethune", "bscore": "7", "schedule": "09:00", "place": "boulogne sur mer"},
  {"date": "15/12/2019", "day": "4", "ateam": "Dunkerque", "ascore": "14", "bteam": "Valenciennes ", "bscore": "6", "schedule": "11:00", "place": "boulogne sur mer"},
  {"date": "12/01/2020", "day": "5", "ateam": "Bethune", "ascore": "3", "bteam": "Douai", "bscore": "3", "schedule": "09:00", "place": "lille"},
  {"date": "12/01/2020", "day": "5", "ateam": "Valenciennes ", "ascore": "9", "bteam": "Dunkerque", "bscore": "8", "schedule": "11:00", "place": "lille"},
  {"date": "26/01/2020", "day": "6", "ateam": "Boulogne sur Mer", "ascore": "3", "bteam": "Dunkerque", "bscore": "7", "schedule": "09:00", "place": "boulogne sur mer"},
  {"date": "26/01/2020", "day": "6", "ateam": "Bethune", "ascore": "5", "bteam": "Valenciennes ", "bscore": "F", "schedule": "11:00", "place": "boulogne sur mer"},
  {"date": "02/02/2020", "day": "7", "ateam": "Douai", "ascore": "", "bteam": "Dunkerque", "bscore": "", "schedule": "09:00", "place": "boulogne sur mer"},
  {"date": "02/02/2020", "day": "7", "ateam": "Boulogne sur Mer", "ascore": "", "bteam": "Valenciennes ", "bscore": "", "schedule": "11:00", "place": "boulogne sur mer"}
  ]
  }
  ]